apiVersion: v1
name: system-upgrade-controller
description: General purpose controller to make system level updates to nodes
home: https://github.com/rancher/system-charts/charts/system-upgrade-controller
sources:
  - "https://github.com/rancher/system-charts/charts/system-upgrade-controller"
version: 0.6.2
appVersion: v0.6.2
