global:
  systemDefaultRegistry: ""

systemUpgradeController:
  image:
    repository: ibuildthecloud/system-upgrade-controller
    tag: latest

kubectl:
  image:
    repository: rancher/kubectl
    tag: v1.18.0
